version: '3.3'
services:
  redis:
    image: redis
    restart: always
    volumes:
    - ./redis-server/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - beingzero
    ports:
      - '6379:6379'

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: stopstalkdb
      MYSQL_ROOT_PASSWORD: root
    ports:
    - '3306:3306'
    volumes:
      - ./mysql-server/data:/var/lib/mysql
    networks:
      - beingzero
    security_opt:
      - seccomp:unconfined

  app:
    build: ./
    networks:
      - beingzero
    ports:
    - '3000:3000'
    - '8000:8000'
    depends_on:
      - "redis"
      - "mysql"

networks:
  beingzero: