version: '3.3'
services:
  redis:
    image: redis
    restart: always
    volumes:
    - ./redis-server/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - beingzero
    ports:
      - '6379:6379'

  mysql:
    image: mysql:5.7
    command: --init-file /application/mysql-server/scripts/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-server/data:/var/lib/mysql
      - ./mysql-server/scripts:/application/mysql-server/scripts
    networks:
      - beingzero
    security_opt:
      - seccomp:unconfined

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - beingzero


  app:
    build: ./
    networks:
      - beingzero
    ports:
    - '3000:3000'
    - '8000:8000'
    command: >
      sh -c "pip install --upgrade pip &&
             pip install -r requirements.txt && 
             python web2py.py -c stalk.crt -k stalk.key -i 0.0.0.0 -a beingzero"
    volumes:
      - ./mysql-server/scripts:/application/mysql-server/scripts
      - ./:/usr/src/stalk/web2py/applications/stopstalk
      - ./models/0firstrun.py.sample:/usr/src/stalk/web2py/applications/stopstalk/models/0firstrun.py
      - ./requirements.txt:/usr/src/stalk/web2py/requirements.txt
    depends_on:
      - "redis"
      - "mysql"

networks:
  beingzero: